#!/usr/bin/env bash
# Configures a new Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/a \ \ \ \ location \/redirect_me {\n \ \ \ \ \ \ \ \ return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n \ \ \ \ }' /etc/nginx/sites-available/default
sudo service nginx reload
