#!/usr/bin/env bash
# Install nginx web server and start it
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sed -i '/server_name _;/c \\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n####' /etc/nginx/sites-available/default
sed -i '/####/c \\terror_page 404 /404.html;\n\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html\/;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
