#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "15i \\\tadd_header X-Served-By 376529-web-01;" /etc/nginx/nginx.conf
sudo service nginx restart
