#!/usr/bin/env bash

sudo apt update

sudo apt install -y haproxy

sudo bash -c 'cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend web_frontend
    bind *:80
    mode http
    default_backend web_backend

backend web_backend
    mode http
    balance roundrobin
    server 376529-web-01 54.157.153.208:80 check
    server 376529-web-02 54.145.155.218:80 check
EOL'

sudo service haproxy restart
