#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
sudo apt update
sudo apt -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt -y update
sudo apt-get -y install haproxy=2.0.33-1ppa1~focal


sudo bash -c 'cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend web_frontend
    bind *:80
    mode http
    default_backend web_backend

backend web_backend
    mode http
    balance roundrobin
    server 376529-web-01 54.157.153.208:80 check
    server 376529-web-02 54.145.155.218:80 check
EOL'

sudo service haproxy restart
