#!/usr/bin/env bash
# Generate MySQL dump and compress the dump to a tar.gz archive

password="$1"
timestamp=$(date +"%d-%m-%Y")

mysqldump -uroot -p"$password" --all-databases > backup.sql
tar -czvf "$timestamp.tar.gz" backup.sql
