#!/usr/bin/env bash
# Get the process ID (PID) of the Gunicorn master process
PID=$(pgrep gunicorn)

if [[ -z $PID ]]; then
    echo "Gunicorn is not running"
fi

# Send a HUP signal to the master process to gracefully reload workers
kill -HUP "$PID"
echo "Gunicorn reloaded gracefully"
